Components/CartSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OnlineBooks.Models;
using Microsoft.AspNetCore.Mvc;

namespace OnlineBooks.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OnlineBooks.Models;

namespace OnlineBooks.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IBooksRespository repository;

        public NavigationMenuViewComponent(IBooksRespository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["category"];

            var categories = repository.Books
                .Select(b => b.Category)
                .Distinct()
                .OrderBy(b => b);

            return View(categories);
        }
    }
}

Views/Shared/ProjectSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Book

<div class="card card-outline-primary m-4 p-4 text-center">
    <div class="container-fluid p-4" style="background-color: #a9a9b9;">
        <!--Bootstrap command 1: container-fluid-->
        <div class="container m-2 p-2" style="background-color: whitesmoke;">
            <!--Bootstrap command 2: container-->
            <h4>@Model.Title</h4>
        </div>

        <ul class="list-inline">
            <!--Bootstrap command 3: list-inline-->
            <li class="list-inline-item m-2"><span style="font-weight:bold">Author:</span> @Model.AuthorFirstName @Model.AuthorMiddleName @Model.AuthorLastName</li>
            <li class="list-inline-item m-2"><span style="font-weight:bold">Publisher:</span> @Model.Publisher</li>
            <li class="list-inline-item m-2"><span style="font-weight:bold">ISBN:</span> @Model.Isbn</li>
            <li><span style="font-weight:bold">Classification:</span> @Model.Classification</li>
            <li><span style="font-weight:bold">Category:</span> @Model.Category</li>
            <li><span style="font-weight:bold">Number of Pages:</span> @Model.NumPages</li>
        </ul>
        <span class="badge badge-pill badge-light">Price: $@Model.Price</span>

    </div>

    <form id="@Model.BookId" asp-page="/Purchase" method="post">
        <input type="hidden" asp-for="BookId"/>                                   <!--Hidden fields help to store data and get it from one place to another-->
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
        <span class="card-text p-1">
            <button type="submit" class="btn-success btn-sm pull-right" style="float:right">
                Add to Cart
            </button>
        </span>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineBooks</title>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body class="bg-light">
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Online Books</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <br />
        <header class="text-center">
            <h1 class="display-1 text-dark">Online Books</h1>
            <vc:navigation-menu />      <!--Category menu inserted here using a view component-->
        </header>

        @RenderBody()

        <div page-model="Model.PagingInfo" page-action="Index" page-classes-enabled="true" page-class="btn"
             page-class-normal="btn-outline-dark"
             page-class-selected="btn-primary" page-url-category="@Model.CurrentCategory"
             class="btn-group pull-right m-1 text-center text-dark">
        </div>
    </div>


</body>
</html>