Pages/Purchase.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OnlineBooks.Models;
using OnlineBooks.Infrastructure;

namespace OnlineBooks.Pages
{
    public class PurchaseModel : PageModel  //inherits from the page model (razor page)
    {
        private IBooksRespository repository;

        //constructor
        public PurchaseModel (IBooksRespository repo, Cart cartService)  
        {
            repository = repo;
            Cart = cartService;
        }

        //properties
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }

        //methods
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }

        public IActionResult OnPost(long bookId, string returnUrl)
        {
            Book book = repository.Books.FirstOrDefault(b => b.BookId == bookId);
            //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();  //add a new cart if one doesn't exist
            Cart.AddItem(book, 1);
            //HttpContext.Session.SetJson("cart", Cart);  //set the json with the updated cart

            return RedirectToPage(new { returnUrl = returnUrl }); //redirect to new page with the new url with whatever has been passed in
        }

        public IActionResult OnPostRemove(long bookId, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(b =>
                b.Book.BookId == bookId).Book);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Pages/Purchase.cshtml
@page
@model OnlineBooks.Pages.PurchaseModel
@{
}

<h2>Your Cart</h2>

<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Book Title</th>
            <th>Quantity</th>
            <th class="text-right">Price</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-left">@line.Book.Title</td>
                <td class="text-center">@line.Quantity</td>
                <td class="text-right">@line.Book.Price</td>
                <td class="text-right">@((line.Quantity * line.Book.Price).ToString("c"))</td>
                <td class="text-center">
                    <form asp-page-handler="Remove" method="post">
                        <input type="hidden" name="BookId"
                               value="@line.Book.BookId" />
                        <input type="hidden" name="returnUrl"
                               value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">
                            Remove
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">@Model.Cart.ComputeTotalSum().ToString("c")</td>
        </tr>
    </tfoot>

</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
</div>